allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// OneDrive can lock files generated by Android's native build tools. Release
// builds may set AIDLINK_GRADLE_BUILD_DIR to use a local temporary directory.
val externalBuildDir = System.getenv("AIDLINK_GRADLE_BUILD_DIR")
val newBuildDir: Directory = if (externalBuildDir.isNullOrBlank()) {
    rootProject.layout.buildDirectory
        .dir("../../build")
        .get()
} else {
    rootProject.layout.dir(
        providers.provider { file(externalBuildDir) },
    ).get()
}
rootProject.layout.buildDirectory.value(newBuildDir)

subprojects {
    val newSubprojectBuildDir: Directory = newBuildDir.dir(project.name)
    project.layout.buildDirectory.value(newSubprojectBuildDir)
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
